### PR TITLE
Copyright & trademark disclaimers, and privacy policy documents for Maskbook File Service

### PR DESCRIPTION
**Pull request by neruthes**

### CODE REVIEW

**Comment by neruthes** [comment]
The URLs of the 2 files remain to be decided.

**Comment by septs** [comment]
typo error

```
plugin/filservice
```

**Comment by neruthes** [comment]
On choosing URLs, I have the following arguments:

- Each plugin can be a result of multiple bilateral cooperations.
- Each bilateral cooperation can lead to the introduction of multiple plugins.
- Multilateral cooperations may possibly occur.
- Therefore, the URLs of such documents should only be associated to the plugin itself.

**Comment by neruthes** [comment]
On the other hand, just like every distribution system like App Store, it is reasonable to assume that every plugin should have an official website(a GitHub repo page can be considered an official website).

With that in mind, the URLs can be:

- `https://dimensiondev.github.io/com.maskbook.fileservice/*`
- `https://fileservice.maskbook.com/*`

**Comment by septs** [comment]
- `https://partner.github.io/[provider-name]/com.maskbook.fileservice/`
- `https://partner.github.io/com.maskbook.fileservice/[provider-name]/`

**Pull request closed without merging**
