### PR TITLE
@yisiliu approved of async/delayed GUN a/b test coming in next CDN

### PR DESCRIPTION
**Pull request by amark**
… added `<script src="https://cdn.jsdelivr.net/npm/gun/gun.js" async></script>` at end last before </body></html>

### CODE REVIEW

**Comment by amark** [comment]
ping

**Comment by Jack-Works** [comment]
I think index.html is a compiled file, you should not modify it directly. cc @BillySh1 can you help to add that script?

and @amark what's your intention to add this script?

**Comment by amark** [comment]
🙄  @yisiliu I told you this was compiled :P see?

He approved of us testing the Rust relay. In the next major version (this was approved by the community + teams with the largest deploys) will A/B test random peers until we can get latency reduced & concurrency improved.

**Comment by Jack-Works** [comment]
> He approved of us testing the Rust relay. In the next major version (this was approved by the community + teams with the largest deploys) will A/B test random peers until we can get latency reduced & concurrency improved.

what delay exactly do you want to test? it doesn't add any gun peer server and the script is from the jsdeliver, how can you collect the statistics data (e.g. wasm loading time, ...etc)?

**Comment by amark** [comment]
In 2 versions from now, the CDN version will have the A/B test ( https://twitter.com/marknadal/status/1493317041620545537 ) and ping a random peer, CPU time on relay will be measured.

Other places I have < 99ms roundtrip query reply time, but I want to keep coding until can sustain that for the 99th percentile across 10K concurrents. Ignoring network timing, this can all be determined relay-side, and will take months of tweaking deploys.

In the future, any new features you guys want to build, we can/could mock them prior to launch to test - that'd be more accurate (not just an idle ping). But we need to get this started meanwhile, please adjust whatever for the merge!

**Comment by Jack-Works** [comment]
> In 2 versions from now, the CDN version will have the A/B test ( https://twitter.com/marknadal/status/1493317041620545537 ) and ping a random peer, CPU time on relay will be measured.

> Other places I have < 99ms roundtrip query reply time, but I want to keep coding until can sustain that for the 99th percentile across 10K concurrents. Ignoring network timing, this can all be determined relay-side, and will take months of tweaking deploys.

Oh, so the A/B test is in the latest gun version itself? I see.

ping @BillySh1 can you see this thread?

**Comment by amark** [comment]
Ping? @yisiliu will you nudge @BillySh1 ?

**Comment by BillySh1** [comment]
This is a compiled file,  i will add it to source code repo and recompile soon you could test

**Comment by BillySh1** [comment]
Script has already added to mask.io, you can start test. This pr will be closed after you reply this :) @amark

**Comment by amark** [comment]
@BillySh1 thanks! I see it, awesome.

(Note: it seems like it might have been added twice, just a heads up. I personally don't care tho)

**Comment by BillySh1** [comment]
> 

yeah i fixed this

**Comment by yisiliu** [comment]
just for ref: #112 #113

**Pull request closed without merging**
